import {
  Paciente,
  AtendimentoIndividual,
  GrupoAtendimento,
  SessaoGrupo,
  Encaminhamento,
} from "./types";

export const INITIAL_PACIENTES: Paciente[] = [
  {
    id: "pac-1",
    nome: "Maria Oliveira da Silva",
    nomeSocial: "Maria Silva",
    cpf: "123.456.789-01",
    rg: "12.345.678-9",
    cartaoSus: "701203456789012",
    dataNascimento: "1968-04-15",
    sexo: "Feminino",
    telefone: "(11) 98765-4321",
    email: "maria.silva@email.com",
    endereco: "Rua das Camélias, 142",
    bairro: "Jardim Primavera",
    cidade: "São Paulo - SP",
    nomeMae: "Aparecida Oliveira",
    vulnerabilidades: ["Idoso(a)", "Baixa Renda", "Isolamento Social"],
    beneficiosSociais: ["BPC / LOAS", "Tarifa Social de Energia"],
    profissoes: "Aposentada / Costureira",
    observacoesAlergias: "Hipertensa, alergia a Dipirona",
    dataCadastro: "2026-01-10",
  },
  {
    id: "pac-2",
    nome: "João Carlos de Souza",
    cpf: "234.567.890-12",
    cartaoSus: "702304567890123",
    dataNascimento: "1985-09-22",
    sexo: "Masculino",
    telefone: "(11) 97123-8899",
    email: "joao.souza@email.com",
    endereco: "Av. dos Trabalhadores, 805, Apto 12",
    bairro: "Centro",
    cidade: "São Paulo - SP",
    nomeMae: "Sônia Carlos de Souza",
    vulnerabilidades: ["Desemprego", "Sobrecarga Emocional"],
    beneficiosSociais: ["Bolsa Família"],
    profissoes: "Auxiliar de Almoxarifado",
    observacoesAlergias: "Sem alergias conhecidas",
    dataCadastro: "2026-02-01",
  },
  {
    id: "pac-3",
    nome: "Ana Paula Ferreira Santos",
    cpf: "345.678.901-23",
    cartaoSus: "703405678901234",
    dataNascimento: "1998-12-03",
    sexo: "Feminino",
    telefone: "(11) 96543-2100",
    endereco: "Rua São Jorge, 45",
    bairro: "Vila Nova",
    cidade: "São Paulo - SP",
    nomeMae: "Elena Ferreira",
    vulnerabilidades: ["Gestante", "Primeira Gestação"],
    beneficiosSociais: ["Bolsa Família"],
    profissoes: "Autônoma",
    observacoesAlergias: "Gestante de 24 semanas. Faz uso de Sulfato Ferroso",
    dataCadastro: "2026-02-15",
  },
  {
    id: "pac-4",
    nome: "Francisco de Assis Santos",
    cpf: "456.789.012-34",
    cartaoSus: "704506789012345",
    dataNascimento: "1955-08-11",
    sexo: "Masculino",
    telefone: "(11) 94321-0987",
    endereco: "Rua dos Girassóis, 310",
    bairro: "Jardim Primavera",
    cidade: "São Paulo - SP",
    nomeMae: "Lúcia dos Santos",
    vulnerabilidades: ["Idoso(a)", "Tabagismo Crônico", "PCD Visula Parcial"],
    beneficiosSociais: ["BPC / LOAS"],
    profissoes: "Aposentado",
    observacoesAlergias: "Portador de DPOC. Tabagista há 40 anos.",
    dataCadastro: "2026-03-01",
  },
  {
    id: "pac-5",
    nome: "Beatriz Lima Rocha",
    cpf: "567.890.123-45",
    cartaoSus: "705607890123456",
    dataNascimento: "2001-06-18",
    sexo: "Feminino",
    telefone: "(11) 98877-6655",
    email: "beatriz.rocha@email.com",
    endereco: "Rua do Comércio, 99",
    bairro: "Centro",
    cidade: "São Paulo - SP",
    nomeMae: "Marta Lima",
    vulnerabilidades: ["Ansiedade Severa", "Estudante"],
    beneficiosSociais: [],
    profissoes: "Estudante Universitária",
    dataCadastro: "2026-03-12",
  },
];

export const INITIAL_ATENDIMENTOS_INDIVIDUAIS: AtendimentoIndividual[] = [
  {
    id: "atend-1",
    pacienteId: "pac-1",
    pacienteNome: "Maria Oliveira da Silva",
    profissionalNome: "Dra. Débora Costa",
    profissionalCargo: "Psicóloga - CRP 03/24682",
    dataHora: "2026-08-04T10:00:00",
    tipoAtendimento: "Acolhimento",
    demandaMotivo: "Sintomas ansiosos, insônia e isolamento social após perda familiar recente.",
    prontuarioNotas: "Atendimento realizado em sala privativa. Paciente relata tristeza profunda e falta de apetite. Apresenta boa receptividade ao acompanhamento. Orientações sobre hábitos de sono e encaminhada para grupo de convivência de idosos.",
    diagnosticoCid: "F41.1 - Ansiedade Generalizada",
    status: "Concluido",
    encaminhadoNaSessao: true,
    encaminhamentoIdGerado: "enc-1",
  },
  {
    id: "atend-2",
    pacienteId: "pac-2",
    pacienteNome: "João Carlos de Souza",
    profissionalNome: "Dr. Roberto Costa",
    profissionalCargo: "Assistente Social",
    dataHora: "2026-08-05T14:30:00",
    tipoAtendimento: "Atendimento Social",
    demandaMotivo: "Solicitação de atualização de CadÚnico e suporte para recolocação profissional.",
    prontuarioNotas: "Entrevista social realizada. Verificada documentação pendente. Atualizado o cadastro familiar e emitido encaminhamento para o centro de qualificação profissional municipal.",
    status: "Concluido",
    encaminhadoNaSessao: true,
    encaminhamentoIdGerado: "enc-2",
  },
  {
    id: "atend-3",
    pacienteId: "pac-3",
    pacienteNome: "Ana Paula Ferreira Santos",
    profissionalNome: "Enfª. Camilla Duarte",
    profissionalCargo: "Enfermeira de Saúde da Família",
    dataHora: "2026-08-06T09:00:00",
    tipoAtendimento: "Consulta Terapêutica",
    demandaMotivo: "Consulta de pré-natal de rotina e adesão ao grupo de gestantes.",
    prontuarioNotas: "Altura uterina compatível com idade gestacional. Batimentos cardíacos fetais normais (142 bpm). Paciente sem queixas agudas. Incluída na turma do Grupo de Gestantes.",
    diagnosticoCid: "Z34 - Acompanhamento de Gravidez Normal",
    status: "Concluido",
  },
  {
    id: "atend-4",
    pacienteId: "pac-4",
    pacienteNome: "Francisco de Assis Santos",
    profissionalNome: "Dr. Marcelo Vieira",
    profissionalCargo: "Médico de Família",
    dataHora: "2026-08-06T11:00:00",
    tipoAtendimento: "Consulta Terapêutica",
    demandaMotivo: "Acompanhamento de DPOC e desejo expresso de parar de fumar.",
    prontuarioNotas: "Paciente motivado para cessação tabágica. Prescrita medicação de apoio. Inserido no Grupo de Prevenção do Tabagismo e emitido encaminhamento para exames espirométricos no hospital de referência.",
    diagnosticoCid: "F17.2 - Dependência de Nicotina / J44 - DPOC",
    status: "Concluido",
    encaminhadoNaSessao: true,
    encaminhamentoIdGerado: "enc-3",
  },
];

export const INITIAL_GRUPOS: GrupoAtendimento[] = [
  {
    id: "grp-1",
    nome: "Grupo Viver Bem - Terceira Idade",
    categoria: "Grupo de Convivência",
    descricao: "Grupo voltado à promoção de saúde, autonomia, trocas de experiências e convivência comunitária para pessoas acima de 60 anos.",
    responsavelNome: "Dra. Débora Costa",
    responsavelCargo: "Psicóloga - CRP 03/24682",
    coResponsavel: "Dr. Roberto Costa (Assistente Social)",
    localSala: "Sala Multiuso A - CRAS / UBS",
    frequencia: "Semanal",
    horarioPadrao: "Toda Terça-feira às 09:30",
    maxVagas: 20,
    participantesIds: ["pac-1", "pac-4"],
    status: "Ativo",
    dataCriacao: "2026-01-15",
  },
  {
    id: "grp-2",
    nome: "Grupo de Apoio Terapêutico e Ansiedade",
    categoria: "Apoio Psicológico",
    descricao: "Encontros focados em estratégias de regulação emocional, psicoeducação e manejo de sintomas de estresse e ansiedade.",
    responsavelNome: "Dra. Débora Costa",
    responsavelCargo: "Psicóloga - CRP 03/24682",
    localSala: "Consultório 3 / Auditório",
    frequencia: "Quinzenal",
    horarioPadrao: "Quarta-feira às 14:00",
    maxVagas: 12,
    participantesIds: ["pac-1", "pac-2", "pac-5"],
    status: "Ativo",
    dataCriacao: "2026-02-01",
  },
  {
    id: "grp-3",
    nome: "Grupo de Gestantes & Puerpério",
    categoria: "Grupo de Gestantes",
    descricao: "Espaço de acolhimento, orientação sobre parto humanizado, amamentação, cuidados com o recém-nascido e apoio emocional.",
    responsavelNome: "Enfª. Camilla Duarte",
    responsavelCargo: "Enfermeira",
    coResponsavel: "Dra. Débora Costa (Psicóloga - CRP 03/24682)",
    localSala: "Sala de Reuniões 2",
    frequencia: "Semanal",
    horarioPadrao: "Toda Quinta-feira às 10:00",
    maxVagas: 15,
    participantesIds: ["pac-3"],
    status: "Ativo",
    dataCriacao: "2026-02-10",
  },
  {
    id: "grp-4",
    nome: "Programa de Prevenção e Cessação do Tabagismo",
    categoria: "Prevenção do Tabagismo",
    descricao: "Sessões estruturadas em 4 encontros para cessação do fumo com apoio comportamental e farmacológico.",
    responsavelNome: "Dr. Marcelo Vieira",
    responsavelCargo: "Médico de Família",
    coResponsavel: "Enfª. Camilla Duarte",
    localSala: "Auditório Central",
    frequencia: "Semanal",
    horarioPadrao: "Quinta-feira às 15:00",
    maxVagas: 10,
    participantesIds: ["pac-4"],
    status: "Ativo",
    dataCriacao: "2026-03-01",
  },
];

export const INITIAL_SESSOES_GRUPO: SessaoGrupo[] = [
  {
    id: "sess-1",
    grupoId: "grp-1",
    grupoNome: "Grupo Viver Bem - Terceira Idade",
    dataHora: "2026-08-04T09:30:00",
    temaSessao: "Autocuidado e Fortalecimento de Vínculos no Envelhecimento",
    pautaDetalhada: "1. Dinâmica do Espelho (Autocuidado)\n2. Roda de conversa sobre rotina e passatempos\n3. Lanche comunitário e encerramento.",
    sinteseRelato: "Excelente adesão. Os participantes compartilharam histórias de superação. Maria Silva participou ativamente e expressou alívio em interagir com o grupo.",
    facilitadorNome: "Dra. Débora Costa",
    presencas: {
      "pac-1": { presente: true, observacaoIndividual: "Muito participativa, interagiu bem." },
      "pac-4": { presente: true, observacaoIndividual: "Relatou melhora no ânimo." },
    },
    totalPresentes: 2,
    totalAusentes: 0,
  },
  {
    id: "sess-2",
    grupoId: "grp-2",
    grupoNome: "Grupo de Apoio Terapêutico e Ansiedade",
    dataHora: "2026-08-05T14:00:00",
    temaSessao: "Técnicas de Respiração Diafragmática e Atenção Plena",
    pautaDetalhada: "1. Apresentação inicial\n2. Exercício guiado de respiração\n3. Identificação de gatilhos ansiosos cotidianos\n4. Combinado para a próxima quinzena.",
    sinteseRelato: "Sessão focada na prática de grounding e respiração. Beatriz Lima reportou redução nos picos de pânico universitários.",
    facilitadorNome: "Dra. Débora Costa",
    presencas: {
      "pac-1": { presente: true, observacaoIndividual: "Praticou os exercícios com tranquilidade." },
      "pac-2": { presente: false, observacaoIndividual: "Ausência justificada por entrevista de emprego." },
      "pac-5": { presente: true, observacaoIndividual: "Relatou episódios recentes de insônia, acolhida pelo grupo." },
    },
    totalPresentes: 2,
    totalAusentes: 1,
  },
];

export const INITIAL_ENCAMINHAMENTOS: Encaminhamento[] = [
  {
    id: "enc-1",
    pacienteId: "pac-1",
    pacienteNome: "Maria Oliveira da Silva",
    pacienteCpf: "123.456.789-01",
    setorOrigem: "Acolhimento de Psicologia",
    profissionalEmissor: "Dra. Débora Costa",
    cargoEmissor: "Psicóloga - CRP 03/24682",
    setorDestino: "CAPS I - Centro de Atenção Psicossocial",
    especialidadeDestino: "Psiquiatria e Acompanhamento Intensivo",
    prioridade: "Prioritário",
    motivoEncaminhamento: "Avaliação psiquiátrica para ajuste medicamentoso e acompanhamento multidisciplinar de quadro ansioso-depressivo.",
    justificativaTecnica: "Usuária apresenta quadro de ansiedade moderada a grave com insônia persistente decorrente de luto recente. Requer avaliação médica psiquiátrica complementar ao suporte psicológico já iniciado no serviço de origem.",
    hipoteseDiagnostica: "F41.1 / F32.1 - Transtorno Ansioso Depressivo",
    dataEmissao: "2026-08-04",
    status: "Em Análise",
  },
  {
    id: "enc-2",
    pacienteId: "pac-2",
    pacienteNome: "João Carlos de Souza",
    pacienteCpf: "234.567.890-12",
    setorOrigem: "Serviço Social - CRAS",
    profissionalEmissor: "Dr. Roberto Costa",
    cargoEmissor: "Assistente Social",
    setorDestino: "Centro Integrado de Apoio ao Trabalhador (CIAT)",
    especialidadeDestino: "Orientação Profissional e Cursos Técnicos",
    prioridade: "Rotina",
    motivoEncaminhamento: "Inserção em programas municipais de qualificação profissional e intermediação de mão de obra.",
    justificativaTecnica: "Usuário responsável pelo sustento familiar, em situação de desemprego recente. Apresenta perfil ativo e qualificação intermediária com interesse em logística e almoxarifado.",
    dataEmissao: "2026-08-05",
    status: "Concluido",
    contraEncaminhamento: {
      id: "ce-1",
      dataParecer: "2026-08-06",
      profissionalDestino: "Fernanda Almeida",
      cargoDestino: "Agente do CIAT",
      parecerTecnico: "Cidadão acolhido e matriculado no Curso de Operação de Logística (Início em 15/08). Encaminhado também para 2 seleções de emprego ativas.",
      condutaAdotada: "Matrícula realizada em curso de qualificação + inclusão no banco de vagas.",
      retornoNecessario: false,
    },
  },
  {
    id: "enc-3",
    pacienteId: "pac-4",
    pacienteNome: "Francisco de Assis Santos",
    pacienteCpf: "456.789.012-34",
    setorOrigem: "UBS - Medicina de Família",
    profissionalEmissor: "Dr. Marcelo Vieira",
    cargoEmissor: "Médico de Família",
    setorDestino: "Hospital das Clínicas - Pneumologia",
    especialidadeDestino: "Pneumologia / Espirometria",
    prioridade: "Urgente",
    motivoEncaminhamento: "Exame de Espirometria e avaliação pneumológica para confirmação de gravidade de DPOC e ajuste de broncodilatadores.",
    justificativaTecnica: "Paciente idoso, tabagista crônico, com dispneia aos médios esforços e episódios de sibilância. Necessita de estadiamento funcional pulmonar para concessão de medicação especial pelo estado.",
    hipoteseDiagnostica: "J44.1 - Doença Pulmonar Obstrutiva Crônica com Exacerbação",
    dataEmissao: "2026-08-06",
    status: "Pendente",
  },
];
