import {
  Paciente,
  AtendimentoIndividual,
  GrupoAtendimento,
  SessaoGrupo,
  Encaminhamento,
  Escola,
  Compromisso,
  CasoPrioritario,
  ItemChecklist,
  Intervencao,
  Atividade,
  PerfilDesenvolvimentoAluno,
  PlanejamentoSessao,
  OrientacaoProfessor,
  AtendimentoFamilia,
  MaterialItem,
  IdeiaProjeto,
  MetaProfissional,
  RelatorioFormal,
} from "./types";

export const INITIAL_PACIENTES: Paciente[] = [
  {
    id: "pac-1",
    nome: "Maria Oliveira da Silva",
    nomeSocial: "Maria Silva",
    cpf: "123.456.789-01",
    rg: "12.345.678-9",
    cartaoSus: "701203456789012",
    dataNascimento: "1968-04-15",
    sexo: "Feminino",
    telefone: "(11) 98765-4321",
    email: "maria.silva@email.com",
    endereco: "Rua das Camélias, 142",
    bairro: "Jardim Primavera",
    cidade: "São Paulo - SP",
    nomeMae: "Aparecida Oliveira",
    vulnerabilidades: ["Idoso(a)", "Baixa Renda", "Isolamento Social"],
    beneficiosSociais: ["BPC / LOAS", "Tarifa Social de Energia"],
    profissoes: "Aposentada / Costureira",
    observacoesAlergias: "Hipertensa, alergia a Dipirona",
    dataCadastro: "2026-01-10",
  },
  {
    id: "pac-2",
    nome: "João Carlos de Souza",
    cpf: "234.567.890-12",
    cartaoSus: "702304567890123",
    dataNascimento: "1985-09-22",
    sexo: "Masculino",
    telefone: "(11) 97123-8899",
    email: "joao.souza@email.com",
    endereco: "Av. dos Trabalhadores, 805, Apto 12",
    bairro: "Centro",
    cidade: "São Paulo - SP",
    nomeMae: "Sônia Carlos de Souza",
    vulnerabilidades: ["Desemprego", "Sobrecarga Emocional"],
    beneficiosSociais: ["Bolsa Família"],
    profissoes: "Auxiliar de Almoxarifado",
    observacoesAlergias: "Sem alergias conhecidas",
    dataCadastro: "2026-02-01",
  },
  {
    id: "pac-3",
    nome: "Ana Paula Ferreira Santos",
    cpf: "345.678.901-23",
    cartaoSus: "703405678901234",
    dataNascimento: "1998-12-03",
    sexo: "Feminino",
    telefone: "(11) 96543-2100",
    endereco: "Rua São Jorge, 45",
    bairro: "Vila Nova",
    cidade: "São Paulo - SP",
    nomeMae: "Elena Ferreira",
    vulnerabilidades: ["Gestante", "Primeira Gestação"],
    beneficiosSociais: ["Bolsa Família"],
    profissoes: "Autônoma",
    observacoesAlergias: "Gestante de 24 semanas. Faz uso de Sulfato Ferroso",
    dataCadastro: "2026-02-15",
  },
  {
    id: "pac-4",
    nome: "Francisco de Assis Santos",
    cpf: "456.789.012-34",
    cartaoSus: "704506789012345",
    dataNascimento: "1955-08-11",
    sexo: "Masculino",
    telefone: "(11) 94321-0987",
    endereco: "Rua dos Girassóis, 310",
    bairro: "Jardim Primavera",
    cidade: "São Paulo - SP",
    nomeMae: "Lúcia dos Santos",
    vulnerabilidades: ["Idoso(a)", "Tabagismo Crônico", "PCD Visula Parcial"],
    beneficiosSociais: ["BPC / LOAS"],
    profissoes: "Aposentado",
    observacoesAlergias: "Portador de DPOC. Tabagista há 40 anos.",
    dataCadastro: "2026-03-01",
  },
  {
    id: "pac-5",
    nome: "Beatriz Lima Rocha",
    cpf: "567.890.123-45",
    cartaoSus: "705607890123456",
    dataNascimento: "2001-06-18",
    sexo: "Feminino",
    telefone: "(11) 98877-6655",
    email: "beatriz.rocha@email.com",
    endereco: "Rua do Comércio, 99",
    bairro: "Centro",
    cidade: "São Paulo - SP",
    nomeMae: "Marta Lima",
    vulnerabilidades: ["Ansiedade Severa", "Estudante"],
    beneficiosSociais: [],
    profissoes: "Estudante Universitária",
    dataCadastro: "2026-03-12",
  },
  {
    id: "pac-6",
    nome: "Pedro Henrique Alves",
    cpf: "678.901.234-56",
    cartaoSus: "706708901234567",
    dataNascimento: "2016-05-09",
    sexo: "Masculino",
    telefone: "(11) 91234-5678",
    endereco: "Rua das Palmeiras, 210",
    bairro: "Jardim Primavera",
    cidade: "São Paulo - SP",
    nomeMae: "Renata Alves",
    vulnerabilidades: ["Dificuldade de Aprendizagem"],
    beneficiosSociais: [],
    dataCadastro: "2026-03-20",
    escolaId: "esc-1",
    serie: "4º ano - Fundamental I",
    professor: "Camila Rodrigues",
    origemEncaminhamento: "Professor(a)",
    hipoteseDiagnostica: "TDAH em investigação",
    frequenciaAtendimento: "Semanal",
    prioridade: "Alta",
    dataPrimeiraSessao: "2026-03-25",
  },
  {
    id: "pac-7",
    nome: "Sofia Martins Cardoso",
    cpf: "789.012.345-67",
    cartaoSus: "707809012345678",
    dataNascimento: "2014-11-22",
    sexo: "Feminino",
    telefone: "(11) 92345-6789",
    endereco: "Av. das Educação, 88",
    bairro: "Centro",
    cidade: "São Paulo - SP",
    nomeMae: "Patrícia Cardoso",
    vulnerabilidades: ["Isolamento Social"],
    beneficiosSociais: [],
    dataCadastro: "2026-04-02",
    escolaId: "esc-2",
    serie: "6º ano - Fundamental II",
    professor: "Roberto Nascimento",
    origemEncaminhamento: "Direção",
    hipoteseDiagnostica: "Ansiedade social",
    frequenciaAtendimento: "Quinzenal",
    prioridade: "Média",
    dataPrimeiraSessao: "2026-04-10",
  },
];

export const INITIAL_ATENDIMENTOS_INDIVIDUAIS: AtendimentoIndividual[] = [
  {
    id: "atend-1",
    pacienteId: "pac-1",
    pacienteNome: "Maria Oliveira da Silva",
    profissionalNome: "Dra. Débora Costa",
    profissionalCargo: "Psicóloga - CRP 03/24682",
    dataHora: "2026-08-04T10:00:00",
    tipoAtendimento: "Acolhimento",
    demandaMotivo: "Sintomas ansiosos, insônia e isolamento social após perda familiar recente.",
    prontuarioNotas: "Atendimento realizado em sala privativa. Paciente relata tristeza profunda e falta de apetite. Apresenta boa receptividade ao acompanhamento. Orientações sobre hábitos de sono e encaminhada para grupo de convivência de idosos.",
    diagnosticoCid: "F41.1 - Ansiedade Generalizada",
    status: "Concluido",
    encaminhadoNaSessao: true,
    encaminhamentoIdGerado: "enc-1",
  },
  {
    id: "atend-2",
    pacienteId: "pac-2",
    pacienteNome: "João Carlos de Souza",
    profissionalNome: "Dr. Roberto Costa",
    profissionalCargo: "Assistente Social",
    dataHora: "2026-08-05T14:30:00",
    tipoAtendimento: "Atendimento Social",
    demandaMotivo: "Solicitação de atualização de CadÚnico e suporte para recolocação profissional.",
    prontuarioNotas: "Entrevista social realizada. Verificada documentação pendente. Atualizado o cadastro familiar e emitido encaminhamento para o centro de qualificação profissional municipal.",
    status: "Concluido",
    encaminhadoNaSessao: true,
    encaminhamentoIdGerado: "enc-2",
  },
  {
    id: "atend-3",
    pacienteId: "pac-3",
    pacienteNome: "Ana Paula Ferreira Santos",
    profissionalNome: "Enfª. Camilla Duarte",
    profissionalCargo: "Enfermeira de Saúde da Família",
    dataHora: "2026-08-06T09:00:00",
    tipoAtendimento: "Consulta Terapêutica",
    demandaMotivo: "Consulta de pré-natal de rotina e adesão ao grupo de gestantes.",
    prontuarioNotas: "Altura uterina compatível com idade gestacional. Batimentos cardíacos fetais normais (142 bpm). Paciente sem queixas agudas. Incluída na turma do Grupo de Gestantes.",
    diagnosticoCid: "Z34 - Acompanhamento de Gravidez Normal",
    status: "Concluido",
  },
  {
    id: "atend-4",
    pacienteId: "pac-4",
    pacienteNome: "Francisco de Assis Santos",
    profissionalNome: "Dr. Marcelo Vieira",
    profissionalCargo: "Médico de Família",
    dataHora: "2026-08-06T11:00:00",
    tipoAtendimento: "Consulta Terapêutica",
    demandaMotivo: "Acompanhamento de DPOC e desejo expresso de parar de fumar.",
    prontuarioNotas: "Paciente motivado para cessação tabágica. Prescrita medicação de apoio. Inserido no Grupo de Prevenção do Tabagismo e emitido encaminhamento para exames espirométricos no hospital de referência.",
    diagnosticoCid: "F17.2 - Dependência de Nicotina / J44 - DPOC",
    status: "Concluido",
    encaminhadoNaSessao: true,
    encaminhamentoIdGerado: "enc-3",
  },
];

export const INITIAL_GRUPOS: GrupoAtendimento[] = [
  {
    id: "grp-1",
    nome: "Grupo Viver Bem - Terceira Idade",
    categoria: "Grupo de Convivência",
    descricao: "Grupo voltado à promoção de saúde, autonomia, trocas de experiências e convivência comunitária para pessoas acima de 60 anos.",
    responsavelNome: "Dra. Débora Costa",
    responsavelCargo: "Psicóloga - CRP 03/24682",
    coResponsavel: "Dr. Roberto Costa (Assistente Social)",
    localSala: "Sala Multiuso A - CRAS / UBS",
    frequencia: "Semanal",
    horarioPadrao: "Toda Terça-feira às 09:30",
    maxVagas: 20,
    participantesIds: ["pac-1", "pac-4"],
    status: "Ativo",
    dataCriacao: "2026-01-15",
  },
  {
    id: "grp-2",
    nome: "Grupo de Apoio Terapêutico e Ansiedade",
    categoria: "Apoio Psicológico",
    descricao: "Encontros focados em estratégias de regulação emocional, psicoeducação e manejo de sintomas de estresse e ansiedade.",
    responsavelNome: "Dra. Débora Costa",
    responsavelCargo: "Psicóloga - CRP 03/24682",
    localSala: "Consultório 3 / Auditório",
    frequencia: "Quinzenal",
    horarioPadrao: "Quarta-feira às 14:00",
    maxVagas: 12,
    participantesIds: ["pac-1", "pac-2", "pac-5"],
    status: "Ativo",
    dataCriacao: "2026-02-01",
  },
  {
    id: "grp-3",
    nome: "Grupo de Gestantes & Puerpério",
    categoria: "Grupo de Gestantes",
    descricao: "Espaço de acolhimento, orientação sobre parto humanizado, amamentação, cuidados com o recém-nascido e apoio emocional.",
    responsavelNome: "Enfª. Camilla Duarte",
    responsavelCargo: "Enfermeira",
    coResponsavel: "Dra. Débora Costa (Psicóloga - CRP 03/24682)",
    localSala: "Sala de Reuniões 2",
    frequencia: "Semanal",
    horarioPadrao: "Toda Quinta-feira às 10:00",
    maxVagas: 15,
    participantesIds: ["pac-3"],
    status: "Ativo",
    dataCriacao: "2026-02-10",
  },
  {
    id: "grp-4",
    nome: "Programa de Prevenção e Cessação do Tabagismo",
    categoria: "Prevenção do Tabagismo",
    descricao: "Sessões estruturadas em 4 encontros para cessação do fumo com apoio comportamental e farmacológico.",
    responsavelNome: "Dr. Marcelo Vieira",
    responsavelCargo: "Médico de Família",
    coResponsavel: "Enfª. Camilla Duarte",
    localSala: "Auditório Central",
    frequencia: "Semanal",
    horarioPadrao: "Quinta-feira às 15:00",
    maxVagas: 10,
    participantesIds: ["pac-4"],
    status: "Ativo",
    dataCriacao: "2026-03-01",
  },
];

export const INITIAL_SESSOES_GRUPO: SessaoGrupo[] = [
  {
    id: "sess-1",
    grupoId: "grp-1",
    grupoNome: "Grupo Viver Bem - Terceira Idade",
    dataHora: "2026-08-04T09:30:00",
    temaSessao: "Autocuidado e Fortalecimento de Vínculos no Envelhecimento",
    pautaDetalhada: "1. Dinâmica do Espelho (Autocuidado)\n2. Roda de conversa sobre rotina e passatempos\n3. Lanche comunitário e encerramento.",
    sinteseRelato: "Excelente adesão. Os participantes compartilharam histórias de superação. Maria Silva participou ativamente e expressou alívio em interagir com o grupo.",
    facilitadorNome: "Dra. Débora Costa",
    presencas: {
      "pac-1": { presente: true, observacaoIndividual: "Muito participativa, interagiu bem." },
      "pac-4": { presente: true, observacaoIndividual: "Relatou melhora no ânimo." },
    },
    totalPresentes: 2,
    totalAusentes: 0,
  },
  {
    id: "sess-2",
    grupoId: "grp-2",
    grupoNome: "Grupo de Apoio Terapêutico e Ansiedade",
    dataHora: "2026-08-05T14:00:00",
    temaSessao: "Técnicas de Respiração Diafragmática e Atenção Plena",
    pautaDetalhada: "1. Apresentação inicial\n2. Exercício guiado de respiração\n3. Identificação de gatilhos ansiosos cotidianos\n4. Combinado para a próxima quinzena.",
    sinteseRelato: "Sessão focada na prática de grounding e respiração. Beatriz Lima reportou redução nos picos de pânico universitários.",
    facilitadorNome: "Dra. Débora Costa",
    presencas: {
      "pac-1": { presente: true, observacaoIndividual: "Praticou os exercícios com tranquilidade." },
      "pac-2": { presente: false, observacaoIndividual: "Ausência justificada por entrevista de emprego." },
      "pac-5": { presente: true, observacaoIndividual: "Relatou episódios recentes de insônia, acolhida pelo grupo." },
    },
    totalPresentes: 2,
    totalAusentes: 1,
  },
];

export const INITIAL_ENCAMINHAMENTOS: Encaminhamento[] = [
  {
    id: "enc-1",
    pacienteId: "pac-1",
    pacienteNome: "Maria Oliveira da Silva",
    pacienteCpf: "123.456.789-01",
    setorOrigem: "Acolhimento de Psicologia",
    profissionalEmissor: "Dra. Débora Costa",
    cargoEmissor: "Psicóloga - CRP 03/24682",
    setorDestino: "CAPS I - Centro de Atenção Psicossocial",
    especialidadeDestino: "Psiquiatria e Acompanhamento Intensivo",
    prioridade: "Prioritário",
    motivoEncaminhamento: "Avaliação psiquiátrica para ajuste medicamentoso e acompanhamento multidisciplinar de quadro ansioso-depressivo.",
    justificativaTecnica: "Usuária apresenta quadro de ansiedade moderada a grave com insônia persistente decorrente de luto recente. Requer avaliação médica psiquiátrica complementar ao suporte psicológico já iniciado no serviço de origem.",
    hipoteseDiagnostica: "F41.1 / F32.1 - Transtorno Ansioso Depressivo",
    dataEmissao: "2026-08-04",
    status: "Em Análise",
  },
  {
    id: "enc-2",
    pacienteId: "pac-2",
    pacienteNome: "João Carlos de Souza",
    pacienteCpf: "234.567.890-12",
    setorOrigem: "Serviço Social - CRAS",
    profissionalEmissor: "Dr. Roberto Costa",
    cargoEmissor: "Assistente Social",
    setorDestino: "Centro Integrado de Apoio ao Trabalhador (CIAT)",
    especialidadeDestino: "Orientação Profissional e Cursos Técnicos",
    prioridade: "Rotina",
    motivoEncaminhamento: "Inserção em programas municipais de qualificação profissional e intermediação de mão de obra.",
    justificativaTecnica: "Usuário responsável pelo sustento familiar, em situação de desemprego recente. Apresenta perfil ativo e qualificação intermediária com interesse em logística e almoxarifado.",
    dataEmissao: "2026-08-05",
    status: "Concluido",
    contraEncaminhamento: {
      id: "ce-1",
      dataParecer: "2026-08-06",
      profissionalDestino: "Fernanda Almeida",
      cargoDestino: "Agente do CIAT",
      parecerTecnico: "Aluno acolhido e matriculado no Curso de Operação de Logística (Início em 15/08). Encaminhado também para 2 seleções de emprego ativas.",
      condutaAdotada: "Matrícula realizada em curso de qualificação + inclusão no banco de vagas.",
      retornoNecessario: false,
    },
  },
  {
    id: "enc-3",
    pacienteId: "pac-4",
    pacienteNome: "Francisco de Assis Santos",
    pacienteCpf: "456.789.012-34",
    setorOrigem: "UBS - Medicina de Família",
    profissionalEmissor: "Dr. Marcelo Vieira",
    cargoEmissor: "Médico de Família",
    setorDestino: "Hospital das Clínicas - Pneumologia",
    especialidadeDestino: "Pneumologia / Espirometria",
    prioridade: "Urgente",
    motivoEncaminhamento: "Exame de Espirometria e avaliação pneumológica para confirmação de gravidade de DPOC e ajuste de broncodilatadores.",
    justificativaTecnica: "Paciente idoso, tabagista crônico, com dispneia aos médios esforços e episódios de sibilância. Necessita de estadiamento funcional pulmonar para concessão de medicação especial pelo estado.",
    hipoteseDiagnostica: "J44.1 - Doença Pulmonar Obstrutiva Crônica com Exacerbação",
    dataEmissao: "2026-08-06",
    status: "Pendente",
  },
];

// ============================================================================
// Módulos adicionados a partir do app PsicoEscolar (versão Lovable)
// ============================================================================

export const INITIAL_ESCOLAS: Escola[] = [
  {
    id: "esc-1",
    nome: "Escola Municipal Paulo Freire",
    diretor: "Maria das Graças Silva",
    coordenador: "Ana Paula Oliveira",
    telefone: "(11) 98765-4321",
    endereco: "Av. da Educação, 450 - Centro",
    diasAtendimento: ["Segunda-feira", "Quarta-feira"],
    horarioAtendimento: "08:00 - 12:00",
    numeroAlunos: 420,
    observacoes:
      "Escola polo para atendimento educacional especializado. Sala de recursos multifuncionais bem equipada.",
  },
  {
    id: "esc-2",
    nome: "Escola Estadual Monteiro Lobato",
    diretor: "Carlos Alberto Santos",
    coordenador: "Juliana Costa",
    telefone: "(11) 97654-3210",
    endereco: "Rua dos Saberes, 120 - Jardim Alvorada",
    diasAtendimento: ["Terça-feira", "Quinta-feira"],
    horarioAtendimento: "13:00 - 17:00",
    numeroAlunos: 580,
    observacoes: "Demanda crescente de casos de regulação emocional nos anos iniciais.",
  },
];

export const INITIAL_COMPROMISSOS: Compromisso[] = [
  {
    id: "comp-1",
    titulo: "Atendimento individual - Pedro Henrique",
    tipo: "Atendimento",
    data: "2026-08-13",
    horaInicio: "09:00",
    horaFim: "09:50",
    escolaId: "esc-1",
    pacienteId: "pac-6",
    local: "Sala de Recursos - Paulo Freire",
    descricao: "Sessão semanal de acompanhamento psicológico.",
    concluido: false,
  },
  {
    id: "comp-2",
    titulo: "Reunião com professora Camila Rodrigues",
    tipo: "Reunião",
    data: "2026-08-13",
    horaInicio: "10:00",
    horaFim: "10:30",
    escolaId: "esc-1",
    pacienteId: "pac-6",
    local: "Sala dos Professores",
    descricao: "Alinhamento de estratégias para o Pedro em sala de aula.",
    concluido: false,
  },
  {
    id: "comp-3",
    titulo: "Devolutiva para a família - Sofia Cardoso",
    tipo: "Devolutiva",
    data: "2026-08-14",
    horaInicio: "14:00",
    horaFim: "14:40",
    escolaId: "esc-2",
    pacienteId: "pac-7",
    local: "Sala de Atendimento - Monteiro Lobato",
    descricao: "Retorno à família sobre a evolução do acompanhamento.",
    concluido: false,
  },
];

export const INITIAL_CASOS_PRIORITARIOS: CasoPrioritario[] = [
  {
    id: "cp-1",
    pacienteId: "pac-6",
    motivoRisco:
      "Suspeita de TDAH sem diagnóstico fechado, com prejuízo escolar significativo e conflitos recorrentes em sala.",
    nivelUrgencia: "Urgente",
    acoesIntensivas: [
      "Encaminhar para avaliação neuropsicológica",
      "Reunião quinzenal com a professora",
    ],
    pendencias: ["Aguardando retorno da avaliação neuropsicológica"],
    atualizadoEm: "2026-08-10",
  },
];

export const INITIAL_CHECKLIST_DIARIO: ItemChecklist[] = [
  { id: "chk-1", texto: "Conferir agenda e atendimentos do dia", concluido: false, padrao: true },
  { id: "chk-2", texto: "Separar materiais das sessões", concluido: false, padrao: true },
  { id: "chk-3", texto: "Registrar evoluções dos atendimentos realizados", concluido: false, padrao: true },
];

export const INITIAL_INTERVENCOES: Intervencao[] = [
  {
    id: "int-1",
    titulo: "Regulação emocional com o Termômetro das Emoções",
    tema: "Autorregulação",
    descricao:
      "Uso de escala visual para identificar e nomear a intensidade emocional antes de aplicar estratégias de autorregulação.",
    objetivos: [
      "Ampliar vocabulário emocional",
      "Reconhecer sinais corporais da emoção",
      "Praticar técnica de respiração guiada",
    ],
    passoAPasso: [
      "Apresentar o termômetro e explicar os níveis",
      "Pedir para a criança indicar como está se sentindo",
      "Guiar respiração 4-7-8 quando o nível estiver alto",
      "Registrar a evolução na ficha de acompanhamento",
    ],
    materiaisSugeridos: ["Cartaz do termômetro das emoções", "Cronômetro"],
  },
  {
    id: "int-2",
    titulo: "Protocolo de habilidades sociais em pequenos grupos",
    tema: "Habilidades sociais",
    descricao: "Sequência de dinâmicas para trabalhar escuta, turno de fala e resolução de conflitos entre pares.",
    objetivos: ["Melhorar interação entre pares", "Reduzir conflitos em sala"],
    passoAPasso: [
      "Roda de apresentação e combinados do grupo",
      "Dinâmica de escuta ativa em duplas",
      "Jogo cooperativo com regras de turno",
      "Fechamento com reflexão guiada",
    ],
  },
];

export const INITIAL_ATIVIDADES: Atividade[] = [
  {
    id: "ativ-1",
    titulo: "Caça-palavras da atenção sustentada",
    idadeMinima: 7,
    idadeMaxima: 11,
    objetivo: "Estimular atenção sustentada e concentração.",
    diagnosticoAlvo: ["TDAH", "Geral"],
    areasEstimuladas: ["Atenção", "Concentração"],
    tempoAplicacaoMinutos: 20,
    materiaisNecessarios: ["Folha impressa", "Lápis de cor"],
    instrucoes: "Aplicar em ambiente com poucos estímulos visuais e sonoros, cronometrando o tempo de execução.",
  },
  {
    id: "ativ-2",
    titulo: "História social sobre esperar a vez",
    idadeMinima: 5,
    idadeMaxima: 9,
    objetivo: "Trabalhar autorregulação e habilidades sociais.",
    diagnosticoAlvo: ["Autismo", "TOD"],
    areasEstimuladas: ["Regulação emocional", "Interação social"],
    tempoAplicacaoMinutos: 15,
    materiaisNecessarios: ["Livro de história social ilustrado"],
    instrucoes: "Ler em voz alta, pausando para perguntas de compreensão e simulação da situação.",
  },
];

export const INITIAL_PERFIS_DESENVOLVIMENTO: PerfilDesenvolvimentoAluno[] = [
  {
    pacienteId: "pac-6",
    areasParaEstimular: ["Atenção", "Concentração", "Controle inibitório"],
    observacoesPorArea: {
      Atenção: "Dificuldade em manter foco por mais de 10 minutos.",
    },
    atualizadoEm: "2026-08-05",
  },
];

export const INITIAL_PLANEJAMENTOS_SESSAO: PlanejamentoSessao[] = [
  {
    id: "plan-1",
    pacienteId: "pac-6",
    data: "2026-08-13",
    objetivo: "Estimular atenção sustentada com jogo de tabuleiro cooperativo.",
    materiais: ["Jogo de tabuleiro", "Cronômetro"],
    atividade: "Caça-palavras da atenção sustentada",
    tecnica: "Reforço positivo intermitente",
    tempoEstimadoMinutos: 45,
    resultadoEsperado: "Aumento do tempo de foco em pelo menos 5 minutos.",
    status: "Planejada",
  },
];

export const INITIAL_ORIENTACOES_PROFESSORES: OrientacaoProfessor[] = [
  {
    id: "orip-1",
    nomeProfessor: "Camila Rodrigues",
    turma: "4º ano B",
    escolaId: "esc-1",
    pacienteId: "pac-6",
    dificuldadeObservada: "Dispersão frequente e dificuldade em concluir tarefas.",
    estrategiasSugeridas: [
      "Dividir tarefas em etapas menores",
      "Posicionar o aluno próximo à professora",
      "Usar reforço positivo verbal",
    ],
    dataOrientacao: "2026-08-06",
    retorno: "Professora relatou melhora parcial após reposicionamento em sala.",
    status: "Em Acompanhamento",
  },
];

export const INITIAL_ATENDIMENTOS_FAMILIA: AtendimentoFamilia[] = [
  {
    id: "fam-1",
    pacienteId: "pac-7",
    data: "2026-08-07",
    responsavelPresente: "Patrícia Cardoso (mãe)",
    assunto: "Retorno sobre isolamento social observado na escola.",
    orientacoes: "Orientada a estimular convívio social fora do ambiente escolar e manter rotina de sono regular.",
    encaminhamentos: "Encaminhada para avaliação com neuropediatra caso não haja melhora em 60 dias.",
    proximoContato: "2026-09-07",
  },
];

export const INITIAL_MATERIAIS: MaterialItem[] = [
  {
    id: "mat-1",
    titulo: "Cartões de Emoções (jogo impresso)",
    categoria: "Cartões de Emoções",
    descricao: "Conjunto de 30 cartões ilustrados para nomear e discutir emoções.",
    localOuLink: "Armário de materiais - Sala de Recursos",
    faixaEtaria: "4 a 10 anos",
    disponivel: true,
  },
  {
    id: "mat-2",
    titulo: "Teste WISC-IV (autorizado)",
    categoria: "Testes Autorizados",
    descricao: "Escala Wechsler de Inteligência para Crianças.",
    localOuLink: "Armário fechado - Consultório",
    faixaEtaria: "6 a 16 anos",
    disponivel: true,
  },
];

export const INITIAL_PROJETOS: IdeiaProjeto[] = [
  {
    id: "proj-1",
    titulo: "Roda de Conversa - Setembro Amarelo",
    tema: "Setembro Amarelo",
    publicoAlvo: "Alunos do Fundamental II",
    objetivo: "Promover conscientização sobre saúde mental e prevenção.",
    atividadesPropostas: ["Roda de conversa", "Mural coletivo", "Distribuição de material informativo"],
    recursosNecessarios: ["Cartolinas", "Folhetos informativos"],
    status: "Em Planejamento",
  },
];

export const INITIAL_METAS_PROFISSIONAIS: MetaProfissional[] = [
  {
    id: "meta-1",
    categoria: "Cursos Desejados",
    titulo: "Curso de Neuropsicologia Infantil",
    descricao: "Aprofundar avaliação de funções executivas em crianças.",
    prazo: "2026-12-01",
    concluida: false,
  },
];

export const INITIAL_RELATORIOS_FORMAIS: RelatorioFormal[] = [
  {
    id: "rel-1",
    pacienteId: "pac-6",
    tipo: "Relatório Psicológico",
    titulo: "Relatório Psicológico - Pedro Henrique Alves",
    data: "2026-08-10",
    autor: "Débora Costa - Psicóloga (CRP 03/24682)",
    conteudo: {
      identificacao:
        "Pedro Henrique Alves, 10 anos, 4º ano do Ensino Fundamental I, Escola Municipal Paulo Freire.",
      motivoEncaminhamento:
        "Encaminhado pela professora regente por dificuldade de manter atenção e concluir atividades em sala de aula.",
      procedimentos:
        "Entrevista com responsável, observação em sala de aula, aplicação de atividades de estimulação da atenção ao longo de 4 sessões.",
      analise:
        "Aluno apresenta sinais compatíveis com dificuldade de atenção sustentada, sem prejuízos significativos em outras áreas do desenvolvimento avaliadas.",
      conclusaoRecomendacoes:
        "Recomenda-se avaliação neuropsicológica complementar e manutenção do acompanhamento psicológico semanal, com orientação continuada à escola e à família.",
    },
    status: "Rascunho",
  },
];
